/*
 * File: app/view/CarsPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarsApp.view.CarsPanel', {
    extend: 'Ext.Panel',

    config: {
        id: 'carsPanel',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'carsTitlebar',
                title: 'Cars',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'back',
                        itemId: 'mybutton',
                        styleHtmlContent: true,
                        ui: 'back',
                        iconMask: true,
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'carList',
                itemId: 'mylist',
                itemTpl: [
                    '<div>{model}</div>'
                ],
                store: 'CarJsonStore'
            },
            {
                xtype: 'panel',
                id: 'carInfo',
                scrollable: true,
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'infoFieldSet',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'top',
                                id: 'img',
                                minHeight: 137,
                                ui: '',
                                width: '100%',
                                src: 'http://localhost:4000/images/135iCoupe.jpg'
                            },
                            {
                                xtype: 'spacer',
                                height: 2
                            },
                            {
                                xtype: 'textfield',
                                id: 'price',
                                label: 'Price',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'mpg',
                                label: 'MPG',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'horsepower',
                                label: 'Horsepower',
                                labelWidth: '40%',
                                readOnly: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'lease',
                                label: 'Lease',
                                labelWidth: '40%',
                                readOnly: true
                            }
                        ]
                    }
                ]
            }
        ]
    }

});