/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarsApp.controller.MainController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            carsPanel: '#carsPanel'
        },

        control: {
            "#carList": {
                itemtap: 'onCarListItemTap'
            },
            "#back": {
                tap: 'onBackTap'
            }
        }
    },

    onCarListItemTap: function(dataview, index, target, record, e, options) {
        var carsPanel = this.getCarsPanel();

        carsPanel.down("#back").show();

        carsPanel.down("#carsTitlebar").setTitle(record.data.model);

        carsPanel.down("#img").setSrc("images/"+record.data.img+".jpg");

        infoFieldSet = carsPanel.down("#infoFieldSet");
        infoFieldSet.down("#price").setValue("$"+record.data.price);
        infoFieldSet.down("#mpg").setValue(record.data.mpg);
        infoFieldSet.down("#horsepower").setValue(record.data.horsepower);
        infoFieldSet.down("#lease").setValue("$"+record.data.lease+"/month");

        carsPanel.setActiveItem(1);
    },

    onBackTap: function(button, e, options) {
        var carsPanel = this.getCarsPanel();
        button.hide();
        carsPanel.down("#carsTitlebar").setTitle("Cars");
        carsPanel.setActiveItem(0);
    }

});